
services:
  selenium-hub:
    image: selenium/hub:4.17.0  # Latest Selenium Grid Hub
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  node-chrome:
    image: selenium/node-chrome:4.17.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2  # Run multiple tests in parallel
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - grid
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g  # Adjust based on your system

  node-firefox:
    image: selenium/node-firefox:4.17.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - grid
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g  # Adjust based on your system

networks:
  grid:
    driver: bridge
